import { useMemo, useState } from 'react';
import type { Dispatch, SetStateAction } from 'react';
import { Activity, Brain, GitCompare, LineChart as LineIcon, Network, Play } from 'lucide-react';
import { CartesianGrid, Line, LineChart, ResponsiveContainer, Scatter, ScatterChart, Tooltip, XAxis, YAxis, BarChart, Bar, Cell } from 'recharts';
import type { AssociationResult, ClusteringResult, ClassificationModelResult, RegressionResult, SummaryResponse } from '../types';
import { api } from '../api';
import { ComparisonPanel } from '../components/ComparisonPanel';
import { Badge, Button, Card, CardBody, CardHeader, Input, Loading, Notice, Select, Table } from '../components/UI';

type AnalyticsTab='association'|'classification'|'regression'|'clustering'|'comparison';
const fmt=(n:number)=>new Intl.NumberFormat('en-IN',{maximumFractionDigits:2}).format(n);

export function AnalyticsPage({ sessionId, data }: { sessionId:string; data:SummaryResponse|null }) {
  const [tab,setTab]=useState<AnalyticsTab>('association'); const [loading,setLoading]=useState(false); const [error,setError]=useState('');
  const cols=data?.profile.column_names||[]; const numeric=data?.profile.numeric_columns||[]; const categorical=data?.profile.categorical_columns||[];
  const [txCol,setTxCol]=useState(cols.includes('TransactionID')?'TransactionID':cols[0]||''); const [itemCol,setItemCol]=useState(cols.includes('ProductName')?'ProductName':cols.find(c=>!numeric.includes(c))||''); const [support,setSupport]=useState('0.03'); const [confidence,setConfidence]=useState('0.4'); const [lift,setLift]=useState('1'); const [assoc,setAssoc]=useState<AssociationResult|null>(null);
  const defaultTarget=categorical.includes('CustomerType')?'CustomerType':categorical[0]||''; const defaultFeatures=numeric.filter(c=>['Age','Income','PurchaseFrequency','TotalAmount','Quantity'].includes(c)).slice(0,5); 
  const [target,setTarget]=useState(defaultTarget); const [features,setFeatures]=useState<string[]>(defaultFeatures.length?defaultFeatures:numeric.slice(0,5)); const [classification,setClassification]=useState<{j48:ClassificationModelResult;naive_bayes:ClassificationModelResult}|null>(null);
  const regressionDefault=numeric.includes('TotalAmount')?'TotalAmount':numeric[0]||''; const regressionFeatures=numeric.filter(c=>c!==regressionDefault).slice(0,5); const [regTarget,setRegTarget]=useState(regressionDefault); const [regFeatures,setRegFeatures]=useState<string[]>(regressionFeatures); const [regression,setRegression]=useState<RegressionResult|null>(null); const [predictionValues,setPredictionValues]=useState<Record<string,string>>({}); const [prediction,setPrediction]=useState<number|null>(null);
  const preferredCluster=['Income','PurchaseFrequency','TotalAmount','Quantity']; const clusterCandidates=[...preferredCluster.filter(c=>numeric.includes(c)), ...numeric.filter(c=>!preferredCluster.includes(c))]; const [clusterFeatures,setClusterFeatures]=useState<string[]>(clusterCandidates.slice(0,4)); const [k,setK]=useState('3'); const [clustering,setClustering]=useState<ClusteringResult|null>(null);
  const toggleFeature=(setter:Dispatch<SetStateAction<string[]>>, c:string)=>setter(v=>v.includes(c)?v.filter(x=>x!==c):[...v,c]);

  const runAssoc=async()=>{setLoading(true);setError('');try{setAssoc(await api.association({session_id:sessionId,transaction_col:txCol,item_col:itemCol,min_support:Number(support),min_confidence:Number(confidence),min_lift:Number(lift)}))}catch(e:any){setError(e.message)}finally{setLoading(false)}};
  const runClass=async()=>{setLoading(true);setError('');try{setClassification(await api.classification({session_id:sessionId,target,features}))}catch(e:any){setError(e.message)}finally{setLoading(false)}};
  const runReg=async()=>{setLoading(true);setError('');try{setRegression(await api.regression({session_id:sessionId,target:regTarget,features:regFeatures}))}catch(e:any){setError(e.message)}finally{setLoading(false)}};
  const runPredict=async()=>{setLoading(true);setError('');try{const r=await api.regressionPredict({session_id:sessionId,target:regTarget,features:regFeatures,values:predictionValues});setPrediction(r.prediction)}catch(e:any){setError(e.message)}finally{setLoading(false)}};
  const runCluster=async()=>{setLoading(true);setError('');try{setClustering(await api.clustering({session_id:sessionId,features:clusterFeatures,k:Number(k)}))}catch(e:any){setError(e.message)}finally{setLoading(false)}};

  return <div><div className="mb-5 grid grid-cols-2 gap-2 rounded-2xl border border-slate-200 bg-white p-2 shadow-soft sm:grid-cols-5">{[
    ['association','Association Rules',Network],['classification','Classification',Brain],['regression','Regression',LineIcon],['clustering','Clustering',Activity],['comparison','Comparison',GitCompare]
  ].map(([key,label,Icon]:any)=><button key={key} onClick={()=>{setTab(key);setError('')}} className={`analytics-tab ${tab===key?'analytics-tab-active':''}`}><Icon size={16}/>{label}</button>)}</div>{error&&<div className="mb-4"><Notice kind="error">{error}</Notice></div>}{loading&&<Loading label="Running data mining analysis..."/>}
  {!loading&&tab==='association'&&<Association data={data} txCol={txCol} setTxCol={setTxCol} itemCol={itemCol} setItemCol={setItemCol} support={support} setSupport={setSupport} confidence={confidence} setConfidence={setConfidence} lift={lift} setLift={setLift} run={runAssoc} result={assoc}/>} 
  {!loading&&tab==='classification'&&<Classification data={data} target={target} setTarget={setTarget} features={features} toggle={(c)=>toggleFeature(setFeatures,c)} run={runClass} result={classification}/>} 
  {!loading&&tab==='regression'&&<Regression data={data} target={regTarget} setTarget={setRegTarget} features={regFeatures} toggle={(c)=>toggleFeature(setRegFeatures,c)} run={runReg} result={regression} predictionValues={predictionValues} setPredictionValues={setPredictionValues} predict={runPredict} prediction={prediction}/>} 
  {!loading&&tab==='clustering'&&<Clustering data={data} features={clusterFeatures} toggle={(c)=>toggleFeature(setClusterFeatures,c)} k={k} setK={setK} run={runCluster} result={clustering}/>}
  {!loading&&tab==='comparison'&&<ComparisonPanel sessionId={sessionId}/>}
  </div>
}

function FeaturePicker({data, features, toggle}:{data:SummaryResponse|null;features:string[];toggle:(c:string)=>void}){return <div className="grid gap-2 sm:grid-cols-2 lg:grid-cols-3">{(data?.profile.numeric_columns||[]).map(c=><button key={c} onClick={()=>toggle(c)} className={`rounded-xl border px-3 py-2.5 text-left text-xs font-medium ${features.includes(c)?'border-indigo-300 bg-indigo-50 text-indigo-700':'border-slate-200 bg-white text-slate-600 hover:bg-slate-50'}`}>{features.includes(c)?'✓ ':''}{c}</button>)}</div>}

function Association({data,txCol,setTxCol,itemCol,setItemCol,support,setSupport,confidence,setConfidence,lift,setLift,run,result}:{data:SummaryResponse|null;txCol:string;setTxCol:(v:string)=>void;itemCol:string;setItemCol:(v:string)=>void;support:string;setSupport:(v:string)=>void;confidence:string;setConfidence:(v:string)=>void;lift:string;setLift:(v:string)=>void;run:()=>void;result:AssociationResult|null}){
 return <><div className="mb-4 flex items-center gap-2"><Badge tone="indigo">Assignment 5</Badge><span className="text-sm text-slate-500">Apriori association rule mining</span></div><Card><CardHeader title="Rule configuration" description="Find products that commonly occur in the same transaction." right={<Button onClick={run}><Play size={15}/> Generate rules</Button>}/><CardBody><div className="grid gap-4 lg:grid-cols-3"><div><label className="label">Transaction ID</label><Select value={txCol} onChange={e=>setTxCol(e.target.value)} options={(data?.profile.column_names||[]).map(c=>({value:c,label:c}))}/></div><div><label className="label">Item / Product</label><Select value={itemCol} onChange={e=>setItemCol(e.target.value)} options={(data?.profile.column_names||[]).map(c=>({value:c,label:c}))}/></div><div><label className="label">Minimum support</label><Input value={support} onChange={e=>setSupport(e.target.value)} type="number" min={0.001} max={1} step={0.01}/></div><div><label className="label">Minimum confidence</label><Input value={confidence} onChange={e=>setConfidence(e.target.value)} type="number" min={0.01} max={1} step={0.05}/></div><div><label className="label">Minimum lift</label><Input value={lift} onChange={e=>setLift(e.target.value)} type="number" min={0} step={0.1}/></div></div></CardBody></Card>
 {result&&<><div className="mt-6 grid gap-4 sm:grid-cols-3"><MetricSmall label="Transactions" value={fmt(result.transaction_count)}/><MetricSmall label="Rules generated" value={fmt(result.rule_count)}/><MetricSmall label="Strongest lift" value={result.rules.length?fmt(Math.max(...result.rules.map(r=>r.lift))):'—'}/></div><div className="mt-6 grid gap-6 xl:grid-cols-[1.2fr_0.8fr]"><Card><CardHeader title="Top association rules" description="Sorted by lift and confidence"/><CardBody><Table columns={[{key:'antecedent',label:'Antecedent'},{key:'consequent',label:'Consequent'},{key:'support',label:'Support'},{key:'confidence',label:'Confidence'},{key:'lift',label:'Lift'}]} rows={result.top_rules.slice(0,12).map(r=>({antecedent:r.antecedent,consequent:r.consequent,support:`${(r.support*100).toFixed(1)}%`,confidence:`${(r.confidence*100).toFixed(1)}%`,lift:r.lift.toFixed(2)}))}/></CardBody></Card><Card><CardHeader title="Support vs confidence"/><CardBody><div className="h-80"><ResponsiveContainer width="100%" height="100%"><ScatterChart><CartesianGrid strokeDasharray="3 3"/><XAxis dataKey="support" name="support" tickFormatter={(v)=>`${Math.round(v*100)}%`} /><YAxis dataKey="confidence" name="confidence" tickFormatter={(v)=>`${Math.round(v*100)}%`} /><Tooltip cursor={{strokeDasharray:'3 3'}} formatter={(v:any,n:any)=>[`${(Number(v)*100).toFixed(1)}%`,n]}/><Scatter data={result.scatter} fill="#4f46e5"/></ScatterChart></ResponsiveContainer></div></CardBody></Card></div><div className="mt-6 rounded-2xl border border-indigo-100 bg-indigo-50 p-4 text-sm text-indigo-800"><div className="font-semibold">Business interpretation</div><div className="mt-1 leading-6">A high-confidence rule means the consequent is frequently present when the antecedent appears. Lift above 1 indicates the pair occurs together more often than would be expected from the consequent's standalone frequency.</div></div></>}
 </>
}

function Classification({data,target,setTarget,features,toggle,run,result}:{data:SummaryResponse|null;target:string;setTarget:(v:string)=>void;features:string[];toggle:(c:string)=>void;run:()=>void;result:{j48:ClassificationModelResult;naive_bayes:ClassificationModelResult}|null}){
 return <><div className="mb-4 flex items-center gap-2"><Badge tone="indigo">Assignments 6–7</Badge><span className="text-sm text-slate-500">J48 / C4.5-style decision tree + Naive Bayes</span></div><Card><CardHeader title="Classification configuration" description="Choose a categorical target and numerical predictors." right={<Button onClick={run}><Play size={15}/> Train both models</Button>}/><CardBody><div><label className="label">Target column</label><Select value={target} onChange={e=>setTarget(e.target.value)} options={(data?.profile.categorical_columns||[]).map(c=>({value:c,label:c}))}/></div><div className="mt-5"><div className="label">Features</div><FeaturePicker data={data} features={features} toggle={toggle}/></div></CardBody></Card>
 {result&&<><div className="mt-6 grid gap-4 lg:grid-cols-2"><ModelPanel title="J48 / C4.5-style Decision Tree" result={result.j48}/><ModelPanel title="Naive Bayes" result={result.naive_bayes}/></div><div className="mt-6"><Card><CardHeader title="Model comparison" description="Metrics are calculated on the held-out test split."/><CardBody><Table columns={[{key:'model',label:'Model'},{key:'accuracy',label:'Accuracy'},{key:'precision',label:'Precision'},{key:'recall',label:'Recall'},{key:'f1',label:'F1 Score'}]} rows={[result.j48,result.naive_bayes].map(r=>({model:r.label,accuracy:`${(r.accuracy*100).toFixed(1)}%`,precision:`${(r.precision*100).toFixed(1)}%`,recall:`${(r.recall*100).toFixed(1)}%`,f1:`${(r.f1*100).toFixed(1)}%`}))}/></CardBody></Card></div></>}
 </>
}
function ModelPanel({title,result}:{title:string;result:ClassificationModelResult}){return <Card><CardHeader title={title}/><CardBody><div className="grid grid-cols-4 gap-2">{[['Accuracy',result.accuracy],['Precision',result.precision],['Recall',result.recall],['F1',result.f1]].map(([l,v]:any)=><div key={l} className="rounded-xl bg-slate-50 p-3"><div className="text-[11px] text-slate-500">{l}</div><div className="mt-1 text-lg font-bold">{(v*100).toFixed(1)}%</div></div>)}</div><div className="mt-5"><div className="mb-2 text-xs font-semibold text-slate-600">Confusion matrix</div><div className="overflow-x-auto"><table className="text-center text-xs"><thead><tr><th className="p-2"></th>{result.labels.map(l=><th key={l} className="p-2 font-semibold">{l}</th>)}</tr></thead><tbody>{result.confusion_matrix.map((row,i)=><tr key={i}><th className="p-2 text-left font-semibold">{result.labels[i]}</th>{row.map((v,j)=><td key={j} className={`min-w-12 rounded-lg p-2 ${i===j?'bg-emerald-50 text-emerald-700':'bg-rose-50 text-rose-700'}`}>{v}</td>)}</tr>)}</tbody></table></div></div>{result.tree_rules&&<details className="mt-5"><summary className="cursor-pointer text-xs font-semibold text-indigo-600">View decision-tree rules</summary><pre className="mt-2 max-h-72 overflow-auto rounded-xl bg-slate-950 p-3 text-[10px] leading-4 text-slate-200">{result.tree_rules}</pre></details>}<div className="mt-4 text-xs text-slate-400">Test samples: {result.test_samples}</div></CardBody></Card>}

function Regression({data,target,setTarget,features,toggle,run,result,predictionValues,setPredictionValues,predict,prediction}:{data:SummaryResponse|null;target:string;setTarget:(v:string)=>void;features:string[];toggle:(c:string)=>void;run:()=>void;result:RegressionResult|null;predictionValues:Record<string,string>;setPredictionValues:Dispatch<SetStateAction<Record<string,string>>>;predict:()=>void;prediction:number|null}){
 return <><div className="mb-4 flex items-center gap-2"><Badge tone="indigo">Assignment 8</Badge><span className="text-sm text-slate-500">Linear regression for numerical sales/revenue prediction</span></div><Card><CardHeader title="Regression configuration" description="Pick a numerical target and predictors." right={<Button onClick={run}><Play size={15}/> Train regression</Button>}/><CardBody><div><label className="label">Target column</label><Select value={target} onChange={e=>setTarget(e.target.value)} options={(data?.profile.numeric_columns||[]).map(c=>({value:c,label:c}))}/></div><div className="mt-5"><div className="label">Predictor features</div><FeaturePicker data={data} features={features} toggle={toggle}/></div></CardBody></Card>
 {result&&<><div className="mt-6 grid gap-4 sm:grid-cols-3"><MetricSmall label="R²" value={result.r2.toFixed(4)}/><MetricSmall label="MAE" value={fmt(result.mae)}/><MetricSmall label="RMSE" value={fmt(result.rmse)}/></div><div className="mt-6 grid gap-6 xl:grid-cols-[1.2fr_0.8fr]"><Card><CardHeader title="Actual vs predicted" description="Held-out test samples"/><CardBody><div className="h-80"><ResponsiveContainer width="100%" height="100%"><LineChart data={result.samples}><CartesianGrid strokeDasharray="3 3"/><XAxis dataKey="actual" type="number" tick={{fontSize:11}}/><YAxis dataKey="predicted" type="number" tick={{fontSize:11}}/><Tooltip/><Line type="monotone" dataKey="actual" stroke="#0f766e" dot={false}/><Line type="monotone" dataKey="predicted" stroke="#4f46e5" dot={false}/></LineChart></ResponsiveContainer></div></CardBody></Card><Card><CardHeader title="Try a prediction" description="Values are interpreted using the trained feature types."/><CardBody><div className="space-y-3">{features.slice(0,6).map(f=><div key={f}><label className="label">{f}</label><Input value={predictionValues[f]??''} onChange={e=>setPredictionValues(v=>({...v,[f]:e.target.value}))} placeholder="Enter value"/></div>)}</div><Button className="mt-4 w-full" onClick={predict}>Predict {target}</Button>{prediction!==null&&<div className="mt-4 rounded-2xl bg-emerald-50 p-4 text-center"><div className="text-xs text-emerald-700">Predicted {target}</div><div className="mt-1 text-2xl font-bold text-emerald-800">₹{fmt(prediction)}</div></div>}</CardBody></Card></div></>}
 </>
}
function Clustering({data,features,toggle,k,setK,run,result}:{data:SummaryResponse|null;features:string[];toggle:(c:string)=>void;k:string;setK:(v:string)=>void;run:()=>void;result:ClusteringResult|null}){
 const points=result?.points||[]; return <><div className="mb-4 flex items-center gap-2"><Badge tone="indigo">Assignment 9</Badge><span className="text-sm text-slate-500">K-Means customer segmentation</span></div><Card><CardHeader title="Clustering configuration" description="Features are aggregated at customer level when CustomerID is present." right={<Button onClick={run}><Play size={15}/> Run K-Means</Button>}/><CardBody><div><div className="label">Customer features</div><FeaturePicker data={data} features={features} toggle={toggle}/></div><div className="mt-5 max-w-xs"><label className="label">Number of clusters (K)</label><Input value={k} onChange={e=>setK(e.target.value)} type="number" min={2} max={8} step={1}/></div></CardBody></Card>
 {result&&<><div className="mt-6 grid gap-4 sm:grid-cols-3"><MetricSmall label="Clusters" value={String(result.k)}/><MetricSmall label="Customers" value={fmt(result.customer_count)}/><MetricSmall label="Silhouette score" value={result.silhouette_score.toFixed(4)}/></div><div className="mt-6 grid gap-6 xl:grid-cols-[1fr_0.9fr]"><Card><CardHeader title="Customer segment map" description={`${result.axes.x} vs ${result.axes.y}`}/><CardBody><div className="h-80"><ResponsiveContainer width="100%" height="100%"><ScatterChart><CartesianGrid strokeDasharray="3 3"/><XAxis dataKey="x" name={result.axes.x}/><YAxis dataKey="y" name={result.axes.y}/><Tooltip cursor={{strokeDasharray:'3 3'}}/><Scatter data={points} fill="#4f46e5"/></ScatterChart></ResponsiveContainer></div></CardBody></Card><Card><CardHeader title="Cluster profiles"/><CardBody><div className="space-y-3">{result.summary.map((r:any)=><div key={r.cluster} className="rounded-xl border border-slate-100 p-3"><div className="flex items-center justify-between"><div className="font-semibold">Cluster {r.cluster}</div><Badge tone="indigo">{r.customers} customers</Badge></div><div className="mt-1 text-xs leading-5 text-slate-500">{r.description}</div><div className="mt-3 grid grid-cols-2 gap-2 text-xs">{features.slice(0,4).map(f=><div key={f} className="rounded-lg bg-slate-50 p-2"><div className="text-slate-400">Avg {f}</div><div className="font-semibold">{r[`avg_${f}`] ?? '—'}</div></div>)}</div></div>)}</div></CardBody></Card></div></>}
 </>
}
function MetricSmall({label,value}:{label:string;value:string}){return <Card><CardBody><div className="text-xs text-slate-500">{label}</div><div className="mt-1 text-xl font-bold">{value}</div></CardBody></Card>}
