import { BarChart3, Boxes, IndianRupee, Receipt, ShoppingBag, Users } from 'lucide-react';
import { Bar, BarChart, CartesianGrid, Cell, Legend, Line, LineChart, Pie, PieChart, ResponsiveContainer, Tooltip, XAxis, YAxis } from 'recharts';
import type { SummaryResponse } from '../types';
import { Badge, Card, CardBody, CardHeader, MetricCard, Notice, PageHeader } from '../components/UI';

export function Dashboard({ data, navigate }: { data: SummaryResponse | null; navigate: (page: any)=>void }) {
  if (!data) return <Notice kind="error">No dataset loaded.</Notice>;
  const fmt = new Intl.NumberFormat('en-IN', { maximumFractionDigits: 0 });
  const money = (n: number) => `₹${fmt.format(n)}`;
  return <>
    <PageHeader eyebrow="Overview" title="Retail analytics dashboard" description="A single workspace connecting your DWM assignments to a real-world retail analytics workflow." right={<Badge tone={data.demo?'amber':'green'}>{data.demo?'Synthetic demo data':'Uploaded dataset'}</Badge>}/>
    <div className="mb-6 rounded-2xl border border-indigo-100 bg-gradient-to-r from-indigo-600 to-indigo-700 p-5 text-white shadow-soft sm:p-6">
      <div className="flex flex-col justify-between gap-4 sm:flex-row sm:items-center"><div><div className="text-xs font-semibold uppercase tracking-[0.18em] text-indigo-200">Assignment 10</div><div className="mt-2 text-xl font-bold sm:text-2xl">Integrated Data Warehousing & Data Mining</div><div className="mt-1 max-w-2xl text-sm leading-6 text-indigo-100">Upload retail data, prepare it, discover product relationships, classify customers, predict revenue, segment customers and explain the results.</div></div><button onClick={()=>navigate('analytics')} className="rounded-xl bg-white/10 px-4 py-2 text-sm font-semibold ring-1 ring-white/20 hover:bg-white/15">Open analytics →</button></div>
    </div>
    <div className="grid gap-4 sm:grid-cols-2 xl:grid-cols-6">
      <MetricCard label="Total Customers" value={fmt.format(data.metrics.total_customers)} icon={<Users size={19}/>} />
      <MetricCard label="Transactions" value={fmt.format(data.metrics.total_transactions)} icon={<Receipt size={19}/>} tone="sky" />
      <MetricCard label="Revenue" value={money(data.metrics.total_revenue)} icon={<IndianRupee size={19}/>} tone="emerald" />
      <MetricCard label="Avg. Transaction" value={money(data.metrics.avg_transaction_value)} icon={<ShoppingBag size={19}/>} tone="amber" />
      <MetricCard label="Products" value={fmt.format(data.metrics.total_products)} icon={<Boxes size={19}/>} />
      <MetricCard label="Records" value={fmt.format(data.metrics.total_records)} icon={<BarChart3 size={19}/>} tone="sky" />
    </div>
    <div className="mt-6 grid gap-6 xl:grid-cols-2">
      <Card><CardHeader title="Monthly sales trend" description="Revenue aggregated by month"/><CardBody><div className="h-72"><ResponsiveContainer width="100%" height="100%"><LineChart data={data.charts.monthly_sales||[]}><CartesianGrid strokeDasharray="3 3" vertical={false}/><XAxis dataKey="month" tick={{fontSize:11}}/><YAxis tickFormatter={(v)=>`₹${Math.round(v/1000)}k`} tick={{fontSize:11}}/><Tooltip formatter={(v:any)=>money(Number(v))}/><Line type="monotone" dataKey="revenue" stroke="#4f46e5" strokeWidth={3} dot={false}/></LineChart></ResponsiveContainer></div></CardBody></Card>
      <Card><CardHeader title="Revenue by category" description="Which product categories contribute most"/><CardBody><div className="h-72"><ResponsiveContainer width="100%" height="100%"><BarChart data={data.charts.category_sales||[]}><CartesianGrid strokeDasharray="3 3" vertical={false}/><XAxis dataKey="category" tick={{fontSize:10}} interval={0} angle={-15} textAnchor="end" height={55}/><YAxis tickFormatter={(v)=>`₹${Math.round(v/1000)}k`} tick={{fontSize:11}}/><Tooltip formatter={(v:any)=>money(Number(v))}/><Bar dataKey="revenue" fill="#6366f1" radius={[6,6,0,0]}/></BarChart></ResponsiveContainer></div></CardBody></Card>
      <Card><CardHeader title="Customer type distribution" description="Transaction mix by customer type"/><CardBody><div className="h-72"><ResponsiveContainer width="100%" height="100%"><PieChart><Pie data={data.charts.customer_type||[]} dataKey="count" nameKey="type" innerRadius={55} outerRadius={90} paddingAngle={3}>{(data.charts.customer_type||[]).map((e,i)=><Cell key={i} fill={['#4f46e5','#0ea5e9','#10b981','#f59e0b'][i%4]}/>)}</Pie><Tooltip/><Legend/></PieChart></ResponsiveContainer></div></CardBody></Card>
      <Card><CardHeader title="Top 10 products" description="Revenue leaders in the current dataset"/><CardBody><div className="h-72"><ResponsiveContainer width="100%" height="100%"><BarChart layout="vertical" data={(data.charts.top_products||[]).slice(0,10)}><CartesianGrid strokeDasharray="3 3" horizontal={false}/><XAxis type="number" tickFormatter={(v)=>`₹${Math.round(v/1000)}k`} tick={{fontSize:11}}/><YAxis type="category" dataKey="product" width={90} tick={{fontSize:10}}/><Tooltip formatter={(v:any)=>money(Number(v))}/><Bar dataKey="revenue" fill="#0f766e" radius={[0,6,6,0]}/></BarChart></ResponsiveContainer></div></CardBody></Card>
      <Card><CardHeader title="Revenue by city" description="Geographic performance where city data exists"/><CardBody><div className="h-72"><ResponsiveContainer width="100%" height="100%"><BarChart data={(data.charts.city_sales||[]).slice(0,8)}><CartesianGrid strokeDasharray="3 3" vertical={false}/><XAxis dataKey="city" tick={{fontSize:10}}/><YAxis tickFormatter={(v)=>`₹${Math.round(v/1000)}k`} tick={{fontSize:11}}/><Tooltip formatter={(v:any)=>money(Number(v))}/><Bar dataKey="revenue" fill="#2563eb" radius={[6,6,0,0]}/></BarChart></ResponsiveContainer></div></CardBody></Card>
      <Card><CardHeader title="Payment method mix" description="Transaction count by payment method"/><CardBody><div className="h-72"><ResponsiveContainer width="100%" height="100%"><BarChart data={data.charts.payment_method||[]}><CartesianGrid strokeDasharray="3 3" vertical={false}/><XAxis dataKey="method" tick={{fontSize:10}} interval={0} angle={-12} textAnchor="end" height={55}/><YAxis tick={{fontSize:11}}/><Tooltip/><Bar dataKey="count" fill="#7c3aed" radius={[6,6,0,0]}/></BarChart></ResponsiveContainer></div></CardBody></Card>
    </div>
    <div className="mt-6 grid gap-6 xl:grid-cols-[1fr_360px]"><Card><CardHeader title="DWM analytics modules" description="Each module maps directly to a laboratory concept"/><CardBody><div className="grid gap-3 sm:grid-cols-2 lg:grid-cols-5">{[
      ['Association Rules','Apriori · frequent products', 'analytics'],['J48 Classification','C4.5-style decision tree','analytics'],['Naive Bayes','Probabilistic classifier','analytics'],['Regression','Linear sales prediction','analytics'],['Clustering','K-Means customer segments','analytics'],
    ].map(([title,sub,page],i)=><button onClick={()=>navigate(page)} key={title} className="group rounded-2xl border border-slate-200 p-4 text-left transition hover:-translate-y-0.5 hover:border-indigo-200 hover:shadow-soft"><div className="text-sm font-semibold">{title}</div><div className="mt-1 text-xs text-slate-500">{sub}</div><div className="mt-3 text-xs font-semibold text-indigo-600 opacity-80 group-hover:opacity-100">Open module {i+1} →</div></button>)}
    </div></CardBody></Card><Card><CardHeader title="Recent dataset activity"/><CardBody><div className="space-y-4"><div className="flex gap-3"><div className="mt-1 h-2.5 w-2.5 rounded-full bg-emerald-500"/><div><div className="text-sm font-semibold">Dataset loaded</div><div className="text-xs text-slate-500">{data.demo?'Synthetic demo dataset':'Uploaded dataset'} is active.</div></div></div><div className="flex gap-3"><div className="mt-1 h-2.5 w-2.5 rounded-full bg-indigo-500"/><div><div className="text-sm font-semibold">Analytics available</div><div className="text-xs text-slate-500">Five data-mining modules can run on the active dataset.</div></div></div><div className="flex gap-3"><div className="mt-1 h-2.5 w-2.5 rounded-full bg-amber-500"/><div><div className="text-sm font-semibold">Quality status</div><div className="text-xs text-slate-500">{data.profile.status}</div></div></div></div></CardBody></Card></div>
  </>;
}
