import { useMemo, useState } from 'react';
import type { ChangeEvent } from 'react';
import { FileSpreadsheet, RefreshCcw, UploadCloud } from 'lucide-react';
import type { SummaryResponse } from '../types';
import { api } from '../api';
import { Badge, Button, Card, CardBody, CardHeader, ExportButton, Input, Notice, PageHeader, Table } from '../components/UI';

export function DatasetPage({ sessionId, data, setSessionId, refresh, setFileName, setDemo }: { sessionId:string; data: SummaryResponse|null; setSessionId:(id:string)=>void; refresh:()=>Promise<void>; setFileName:(s:string)=>void; setDemo:(b:boolean)=>void }) {
  const [search,setSearch]=useState(''); const [sortKey,setSortKey]=useState(''); const [sortAsc,setSortAsc]=useState(true); const [page,setPage]=useState(1); const pageSize=10; const [loading,setLoading]=useState(false); const [error,setError]=useState(''); const [message,setMessage]=useState('');
  const preview = useMemo(()=> { const rows=(data?.profile.preview||[]).filter(row=>Object.values(row).some(v=>String(v??'').toLowerCase().includes(search.toLowerCase()))); if(!sortKey) return rows; return [...rows].sort((a,b)=>String(a[sortKey]??'').localeCompare(String(b[sortKey]??''),undefined,{numeric:true,sensitivity:'base'})*(sortAsc?1:-1)); }, [data,search,sortKey,sortAsc]); const totalPages=Math.max(1,Math.ceil(preview.length/pageSize)); const paged=preview.slice((page-1)*pageSize,page*pageSize);
  const columns = data?.profile.column_names.slice(0,12).map(k=>({key:k,label:k}))||[];
  const upload = async (e:ChangeEvent<HTMLInputElement>)=>{ const file=e.target.files?.[0]; if(!file)return; setLoading(true);setError('');setMessage(''); try { const res=await api.upload(file); setSessionId(res.session_id); setFileName(res.file_name); setDemo(false); setPage(1); setMessage(`Uploaded ${res.file_name} successfully.`);} catch(err:any){setError(err.message)} finally{setLoading(false)}};
  const reset = async ()=>{setLoading(true);setError(''); try{await api.reset(sessionId); setDemo(true);setFileName('retail_transactions.csv'); await refresh(); setMessage('Reset to the synthetic demo dataset.')}catch(err:any){setError(err.message)}finally{setLoading(false)}};
  if(!data)return null;
  return <>
    <PageHeader eyebrow="Data layer" title="Dataset management" description="Upload CSV/XLSX data, inspect its quality, and keep one dataset flowing through every DWM module." right={<div className="flex gap-2"><Button onClick={reset} variant="secondary" disabled={loading}><RefreshCcw size={16}/> Reset demo</Button><label className="inline-flex cursor-pointer items-center gap-2 rounded-xl bg-indigo-600 px-4 py-2.5 text-sm font-semibold text-white hover:bg-indigo-700"><UploadCloud size={16}/> Upload dataset<input type="file" accept=".csv,.xlsx,.xls" onChange={upload} className="hidden"/></label></div>}/>
    {error&&<div className="mb-4"><Notice kind="error">{error}</Notice></div>}{message&&<div className="mb-4"><Notice kind="success">{message}</Notice></div>}
    <div className="grid gap-6 xl:grid-cols-[1fr_340px]">
      <Card><CardHeader title="Dataset overview" description="Current file and schema profile" right={<Badge tone={data.demo?'amber':'green'}>{data.demo?'Synthetic demo':'Uploaded'}</Badge>}/><CardBody><div className="grid gap-3 sm:grid-cols-3 lg:grid-cols-6">{[["Rows",data.profile.rows],["Columns",data.profile.columns],["Numerical",data.profile.numeric_columns.length],["Categorical",data.profile.categorical_columns.length],["Date columns",data.profile.date_columns.length],["Missing cells",data.profile.missing_values]].map(([l,v])=><div key={String(l)} className="rounded-xl bg-slate-50 p-4"><div className="text-xs text-slate-500">{l}</div><div className="mt-1 text-xl font-bold">{v}</div></div>)}</div><div className="mt-5 flex flex-wrap items-center gap-2"><Badge tone={data.profile.status==='Dataset Ready for Analysis'?'green':'amber'}>{data.profile.status}</Badge><span className="text-xs text-slate-400">Dataset stays available while you navigate the app.</span></div></CardBody></Card>
      <Card><CardHeader title="Data quality checks"/><CardBody><div className="space-y-3">{[
        ['Missing values',data.profile.missing_values],['Duplicate records',data.profile.duplicate_records],['Negative quantities',data.profile.negative_quantities],['Negative prices',data.profile.negative_prices],['Invalid dates',data.profile.invalid_dates]
      ].map(([l,v])=><div key={String(l)} className="flex items-center justify-between rounded-xl border border-slate-100 px-3 py-2.5"><span className="text-sm text-slate-600">{l}</span><Badge tone={Number(v)===0?'green':'amber'}>{String(v)}</Badge></div>)}</div><div className="mt-4"><ExportButton label="Download current CSV" onClick={()=>window.open(api.cleanCsvUrl(sessionId),'_blank')}/></div></CardBody></Card>
    </div>
    <div className="mt-6"><Card><CardHeader title="Dataset preview" description={`Showing ${preview.length ? (page-1)*pageSize+1 : 0}-${Math.min(page*pageSize,preview.length)} of ${preview.length} matching preview rows`} right={<Input value={search} onChange={e=>setSearch(e.target.value)} placeholder="Search records..."/>}/><CardBody className="p-0"><div className="overflow-x-auto"><table className="min-w-[1050px] w-full text-sm"><thead className="bg-slate-50 text-left text-xs uppercase tracking-wider text-slate-500"><tr>{columns.map(c=><th key={c.key} className="px-4 py-3"><button onClick={()=>{setSortKey(c.key);setSortAsc(k=>sortKey===c.key?!k:true)}} className="font-semibold hover:text-slate-900">{c.label} {sortKey===c.key?(sortAsc?'↑':'↓'):''}</button></th>)}</tr></thead><tbody className="divide-y divide-slate-100">{paged.map((row,i)=><tr key={i} className="hover:bg-slate-50/70">{columns.map(c=><td key={c.key} className="whitespace-nowrap px-4 py-3 text-slate-700">{String(row[c.key]??'—')}</td>)}</tr>)}</tbody></table></div><div className="flex items-center justify-between border-t border-slate-100 px-4 py-3 text-xs text-slate-500"><span>Page {page} of {totalPages}</span><div className="flex gap-2"><button disabled={page<=1} onClick={()=>setPage(p=>Math.max(1,p-1))} className="rounded-lg border border-slate-200 px-3 py-1.5 disabled:opacity-40">Previous</button><button disabled={page>=totalPages} onClick={()=>setPage(p=>Math.min(totalPages,p+1))} className="rounded-lg border border-slate-200 px-3 py-1.5 disabled:opacity-40">Next</button></div></div></CardBody></Card></div>
    <div className="mt-6 rounded-2xl border border-indigo-100 bg-indigo-50 p-4 text-sm text-indigo-800"><div className="font-semibold">Academic note</div><div className="mt-1 leading-6">The included demo dataset is synthetic and intended for academic demonstration. Uploading another dataset recalculates dashboard metrics and model results.</div></div>
  </>;
}
