import { ArrowDown, Database, FileSpreadsheet, GitBranch, Layers3 } from 'lucide-react';
import { Card, CardBody, CardHeader, PageHeader } from '../components/UI';

const assignments=[
 [1,'Data Warehouse & Architecture','Centralized retail data, fact and dimension concepts, and the ETL-style flow.'],
 [2,'WEKA Tool','WEKA experimentation and model-learning workflow.'],
 [3,'Dataset Creation','Synthetic retail transaction data with customer, product and sales attributes.'],
 [4,'Data Preprocessing','Missing values, duplicates, IQR outliers, encoding and normalization.'],
 [5,'Association Rule Mining','Apriori frequent itemsets and association rules.'],
 [6,'J48 Classification','Entropy-based decision tree as a practical J48/C4.5-style implementation.'],
 [7,'Naive Bayes Classification','Probabilistic classification after feature preprocessing.'],
 [8,'Regression','Linear regression for numerical sales/revenue prediction.'],
 [9,'Clustering','K-Means customer segmentation using scaled features.'],
 [10,'Integrated DWM Mini Project','All of the above connected in one retail analytics platform.'],
];
export function DWMPage(){return <><PageHeader eyebrow="Academic mapping" title="DWM concepts & architecture" description="Use this page during your practical and viva to explain exactly how Assignment 10 integrates Assignments 1–9."/><Card><CardHeader title="End-to-end data flow"/><CardBody><div className="flex flex-col items-center gap-2">{['Data Source','Data Warehouse','ETL / Preprocessing','Clean Data','Data Mining','Analytics','Business Insights'].map((x,i)=><div key={x} className="flex w-full max-w-xl flex-col items-center"><div className={`w-full rounded-xl border p-3 text-center text-sm font-semibold ${i===6?'border-emerald-200 bg-emerald-50 text-emerald-700':'border-indigo-100 bg-indigo-50 text-indigo-700'}`}>{x}</div>{i<6&&<ArrowDown size={17} className="my-1 text-slate-300"/>}</div>)}</div></CardBody></Card>
 <div className="mt-6 grid gap-6 xl:grid-cols-[1fr_1fr]"><Card><CardHeader title="Star schema (conceptual)" description="Simplified retail data warehouse representation"/><CardBody><div className="grid grid-cols-1 gap-4 sm:grid-cols-2"><div className="rounded-2xl border-2 border-indigo-200 bg-indigo-50 p-4 sm:col-span-2"><div className="flex items-center gap-2 font-bold text-indigo-700"><Database size={18}/> Fact_Sales</div><div className="mt-3 grid grid-cols-2 gap-2 text-xs text-slate-600 sm:grid-cols-3">{['TransactionID','CustomerID','ProductID','DateID','Quantity','Amount'].map(x=><span key={x} className="rounded-lg bg-white px-2 py-2 ring-1 ring-indigo-100">{x}</span>)}</div></div>{[['Dim_Customer', ['CustomerID','Age','Gender','Income','City']],['Dim_Product',['ProductID','ProductName','Category']],['Dim_Date',['DateID','Date','Month','Quarter','Year']],['Dim_Store',['StoreID','StoreName','City']]].map(([title,items])=><div key={String(title)} className="rounded-2xl border border-slate-200 p-4"><div className="font-semibold">{title}</div><div className="mt-3 space-y-1 text-xs text-slate-500">{(items as string[]).map(x=><div key={x} className="flex gap-2"><span className="text-indigo-500">•</span>{x}</div>)}</div></div>)}</div></CardBody></Card><Card><CardHeader title="WEKA academic workflow"/><CardBody><div className="rounded-2xl bg-slate-950 p-5 text-sm text-slate-200"><div>Dataset</div><div className="my-2 text-slate-500">↓</div><div>WEKA experimentation</div><div className="my-2 text-slate-500">↓</div><div>Algorithm evaluation</div><div className="my-2 text-slate-500">↓</div><div>Final web application implementation</div></div><div className="mt-4 text-sm leading-6 text-slate-500">J48 is the WEKA name associated with a C4.5 decision-tree classifier. This project exposes the equivalent role through the application and clearly labels the Python implementation as J48/C4.5-style.</div></CardBody></Card></div>
 <div className="mt-6 grid gap-3 sm:grid-cols-2">{assignments.map(([num,title,desc])=><div key={String(num)} className="rounded-2xl border border-slate-200 bg-white p-4 shadow-soft"><div className="flex items-start gap-3"><div className="flex h-9 w-9 shrink-0 items-center justify-center rounded-xl bg-indigo-50 text-xs font-bold text-indigo-700">{num}</div><div><div className="font-semibold">Assignment {num} · {title}</div><div className="mt-1 text-sm leading-6 text-slate-500">{desc}</div></div></div></div>)}</div></>}
