import { useEffect, useState } from 'react';
import { Download, Lightbulb, RefreshCcw } from 'lucide-react';
import type { SummaryResponse } from '../types';
import { api } from '../api';
import { Badge, Button, Card, CardBody, CardHeader, Notice, PageHeader } from '../components/UI';

export function InsightsPage({sessionId,data}:{sessionId:string;data:SummaryResponse|null}){
 const [insights,setInsights]=useState<string[]>([]); const [loading,setLoading]=useState(false); const [error,setError]=useState('');
 const load=async()=>{setLoading(true);setError('');try{const r=await api.insights(sessionId);setInsights(r.insights)}catch(e:any){setError(e.message)}finally{setLoading(false)}};
 useEffect(()=>{load()},[sessionId]);
 const downloadResults=()=>{const payload={dataset:data?.profile,metrics:data?.metrics,insights}; const blob=new Blob([JSON.stringify(payload,null,2)],{type:'application/json'}); const a=document.createElement('a'); a.href=URL.createObjectURL(blob); a.download='RetailSense_results.json'; a.click(); URL.revokeObjectURL(a.href)};
 const downloadReport=()=>{const title='RetailSense — DWM Analytics Report'; const html=`<!doctype html><html><head><meta charset="utf-8"><title>${title}</title><style>body{font-family:Arial,sans-serif;padding:40px;color:#172033;line-height:1.6}h1{color:#3730a3}h2{margin-top:28px;border-bottom:1px solid #ddd;padding-bottom:6px}.card{background:#f8fafc;padding:16px;border-radius:12px;margin:10px 0}small{color:#64748b}</style></head><body><h1>${title}</h1><small>Generated from ${data?.demo?'synthetic demo data':'uploaded dataset'}.</small><h2>Dataset Summary</h2><div class="card">Records: ${data?.metrics.total_records||0}<br>Customers: ${data?.metrics.total_customers||0}<br>Transactions: ${data?.metrics.total_transactions||0}<br>Revenue: ₹${new Intl.NumberFormat('en-IN').format(data?.metrics.total_revenue||0)}</div><h2>Key Findings</h2>${insights.map(x=>`<div class="card">${x}</div>`).join('')}<h2>DWM Modules</h2><div class="card">Preprocessing · Apriori Association Rules · J48/C4.5-style Classification · Naive Bayes · Linear Regression · K-Means Clustering</div><p><small>Demo data is synthetic and intended for academic demonstration. Model metrics and mining outputs in the application are calculated from the active dataset.</small></p></body></html>`; const blob=new Blob([html],{type:'text/html'}); const a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download='RetailSense_DWM_Report.html';a.click();URL.revokeObjectURL(a.href)};
 return <><PageHeader eyebrow="Decision layer" title="Insights & reports" description="A consolidated view of data quality, retail patterns and machine-learning outputs." right={<div className="flex gap-2"><Button variant="secondary" onClick={load} disabled={loading}><RefreshCcw size={15}/> Refresh</Button><Button variant="secondary" onClick={downloadResults}><Download size={15}/> Export results</Button><Button onClick={downloadReport}><Download size={15}/> Export report</Button></div>}/>{error&&<Notice kind="error">{error}</Notice>}<div className="grid gap-6 lg:grid-cols-2"><Card><CardHeader title="Key findings" description="Derived from the active dataset"/><CardBody><div className="space-y-3">{(loading?[]:insights).map((x,i)=><div key={i} className="flex gap-3 rounded-xl border border-slate-100 p-4"><div className="mt-0.5 rounded-lg bg-amber-50 p-2 text-amber-600"><Lightbulb size={16}/></div><div className="text-sm leading-6 text-slate-700">{x}</div></div>)}{!loading&&!insights.length&&<div className="text-sm text-slate-500">No insights available yet.</div>}</div></CardBody></Card><Card><CardHeader title="Current dataset health"/><CardBody><div className="space-y-3">{[['Records',data?.profile.rows||0],['Missing cells',data?.profile.missing_values||0],['Duplicates',data?.profile.duplicate_records||0],['Negative quantities',data?.profile.negative_quantities||0],['Invalid dates',data?.profile.invalid_dates||0]].map(([l,v])=><div key={String(l)} className="flex items-center justify-between rounded-xl bg-slate-50 px-4 py-3 text-sm"><span className="text-slate-500">{l}</span><span className="font-semibold">{String(v)}</span></div>)}</div><div className="mt-4"><Badge tone={data?.profile.status==='Dataset Ready for Analysis'?'green':'amber'}>{data?.profile.status||'Unknown'}</Badge></div></CardBody></Card></div><div className="mt-6"><Card><CardHeader title="DWM project coverage"/><CardBody><div className="grid gap-3 md:grid-cols-3 lg:grid-cols-5">{['Preprocessing','Association Rules','J48','Naive Bayes','Regression','Clustering','Data Warehouse','WEKA Workflow','Dataset Creation','Assignment 10'].map((x,i)=><div key={x} className="rounded-xl border border-slate-100 p-4"><div className="text-xs font-semibold text-indigo-600">{String(i+1).padStart(2,'0')}</div><div className="mt-1 text-sm font-semibold">{x}</div><div className="mt-1 text-xs text-slate-400">Covered in the integrated workflow.</div></div>)}</div></CardBody></Card></div></>;
}
